# Generated by Django 4.2.3 on 2023-07-13 13:48

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone num format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Not to disclose')], default=None, max_length=1)),
                ('whatsapp', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone num format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('identification', models.CharField(choices=[('social_id', 'Social ID'), ('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport')], default=None, max_length=20)),
                ('identification_detail', models.CharField(default=None, max_length=50)),
                ('data_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=256)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('pyma_activity', models.CharField(max_length=100)),
                ('volunteering_week_hrs', models.DecimalField(decimal_places=0, max_digits=3)),
                ('volunteering_brief', models.CharField(max_length=100)),
                ('volunteering_detail', models.TextField(max_length=256)),
                ('meditation_exp_years', models.DecimalField(decimal_places=0, max_digits=2)),
                ('meditation_brief', models.CharField(max_length=100)),
                ('meditation_detail', models.TextField(max_length=256)),
                ('contribution', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=100)),
                ('hobby_level', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('optional_details', models.TextField(max_length=256)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=8)),
                ('yfs_knowlege', models.CharField(max_length=15)),
                ('comments_questions', models.TextField(max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
