# Generated by Django 4.2.3 on 2023-07-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_customuser_data_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='meditation_exp_years',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='volunteering_week_hrs',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
