# Generated by Django 4.2.3 on 2023-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
